export const projectConst = {
      PRO_CREATE_REQUEST: 'PRO_CREATE_REQUEST',
      PRO_CREATE_SUCCESS: 'PRO_CREATE_SUCCESS',
      PRO_CREATE_FAILURE: 'PRO_CREATE_FAILURE',
      // PASS Editing
      PRO_EDITTING: 'PRO_EDITTING',
      // EDITTING 
      PRO_EDITTING_REQUEST: 'PRO_EDITTING_REQUEST',
      PRO_EDITTING_SUCCESS: 'PRO_EDITTING_SUCCESS',
      PRO_EDITTING_FAILURE: 'PRO_EDITTING_FAILURE',
      // DELETE
      PRO_DELETE_REQUEST: 'PRO_DELETE_REQUEST',
      PRO_DELETE_SUCCESS: 'PRO_DELETE_SUCCESS',
      PRO_DELETE_FAILURE: 'PRO_DELETE_FAILURE'
}