export const TASK = {
  //Fetch
  FETCH_TASK_REQUEST: 'FETCH_TASK_REQUEST',
  FETCH_TASK_SUCCESS: 'FETCH_TASK_SUCCESS',
  FETCH_TASK_FAILURE: 'FETCH_TASK_FAILURE',
  //TASK_EDITING
  TASK_EDITING: 'TASK_EDITING',
  // Edit
  TASK_EDIT_REQUEST: 'TASK_EDIT_REQUEST',
  TASK_EDIT_SUCCESS: 'TASK_EDIT_SUCCESS',
  TASK_EDIT_FAILURE: 'TASK_EDIT_FAILURE',
  // TASK_ADD_NEW
  TASK_ADD_NEW_REQUEST: 'TASK_ADD_NEW_REQUEST',
  TASK_ADD_NEW_SUCCESS: 'TASK_ADD_NEW_SUCCESS',
  TASK_ADD_NEW_FAILURE: 'TASK_ADD_NEW_FAILURE',
  // TASK_DELETE_
  TASK_DELETE_REQUEST: 'TASK_DELETE_REQUEST',
  TASK_DELETE_SUCCESS: 'TASK_DELETE_SUCCESS',
  TASK_DELETE_FAILURE: 'TASK_DELETE_FAILURE',
  //TASK_SEARCH_
  TASK_SEARCH_REQUEST: 'TASK_SEARCH_REQUEST',
  TASK_SEARCH_SUCCESS: 'TASK_SEARCH_SUCCESS',
  TASK_SEARCH_FAILURE: 'TASK_SEARCH_FAILURE',
};

export const TASK_STATUS = [
  {
    value: 0,
    label: 'To do',
  },
  {
    value: 1,
    label: 'In progress',
  },
  {
    value: 2,
    label: 'Done',
  },
  {
    value: 3,
    label: 'Pending'
  }
];
